_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 63
                - 71
                - 98
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 63
                - 71
                - 98
                - 105
            "3":
                - 1
                - 13
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "6": 4.30.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
